# Use docker-based infrastructure
sudo: false

language: java

jdk: oraclejdk7

notifications:
  irc: "chat.freenode.net#seedstack-dev"

cache:
  directories:
    - "$HOME/.m2/repository"

script: mvn -B verify jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN

after_success:
  - echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>\${env.SONATYPE_USER}</username><password>\${env.SONATYPE_PASS}</password></server></servers></settings>" > ~/settings.xml
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" && $TRAVIS_BRANCH == \"master\" ]] && mvn deploy --settings ~/settings.xml -DskipTests=true -Dmaven.javadoc.skip=true"
